apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: bftojs5svohz4c
    access: proxy
    url: http://10.0.0.100:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
