name: Aos virtual machine build
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
      release_date: ${{ steps.version.outputs.release_date }}

    steps:
      - name: Set release version
        id: version
        run: |
          tag=$(basename "${{ github.ref }}")
          version=${tag#"v"}
          release_date="$(date -I)"

          echo "Release tag:     $tag"
          echo "Release version: $version"
          echo "Release date:    $release_date"

          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "release_date=$release_date" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: github-arc-x64-dind
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        machine: [qemux86-64, qemuarm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: aosedge/meta-aos-vm
          fetch-depth: 0

      - name: Build
        run: |
          echo "Build version: ${{ needs.prepare.outputs.version }}"
          echo "Build machine: ${{ matrix.machine }}"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Release
        run: |
          echo "Release version: ${{ needs.prepare.outputs.version }}"

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    steps:
      - name: Cleanup
        run: |
          echo "Cleanup version: ${{ needs.prepare.outputs.version }}"
